# Nb processes of nginx
worker_processes		auto;

events {
    worker_connections		64;			 # Max nb of connections per worker
}

http {
    include			/etc/nginx/mime.types;		# to associate text/html, images/jpeg, ...
    default_type		application/octet-stream;	# if not recognize

    # logs
    access_log			/var/log/nginx/access.log;
    error_log			/var/log/nginx/error.log;

    server {
	listen			443 ssl;
	server_name		lefoffan.42.fr;

	# certificates
	ssl_certificate		/etc/nginx/ssl/inception.crt;
	ssl_certificate_key	/etc/nginx/ssl/inception.key;
	ssl_protocols		TLSv1.2 TLSv1.3;

	root			/var/www/wordpress;
	server_name		lefoffan.42.fr;
	index			index.php index.html;

	# redirection when an error occured
	location / {
	    try_files		$uri $uri/ /index.php$is_args$args;
	}

	# redirect all php request to wordpress (NGINX don't have php)
	location ~ \.php$ {
	    include		snippets/fastcgi-php.conf;
	    fastcgi_pass	wordpress:9000;
	}
    }
}

